### ISSUE TITLE
HA SS Error after HA Core Update from 2023.4.5 to 2023.4.6

### ISSUE THREAD

**Issue by stbrun** [briis/securityspy#48]
Hello Briis

I got the following error and SS was not able to start in HA:

Logger: homeassistant.setup
Source: setup.py:213 
First occurred: 09:54:50 (1 occurrences) 
Last logged: 09:54:50

Setup failed for custom integration securityspy: Unable to import component: cannot import name 'InvalidCredentials' from 'pysecspy.errors' (/usr/local/lib/python3.10/site-packages/pysecspy/errors.py)

The error occurred after upgrading HA core from 2023.4.5 to 2023.4.6.

Could you please help me with this? Thanks for your support!
Stefan

**Comment by stbrun** [comment]
Went back to old version via backup and installed the update again. everything ok.
